### PR TITLE
Koin Fragment-Factory

### LINKED ISSUE #15: Koin FragmentFactory
easy constructor injection of fragments:
https://github.com/InsertKoinIO/koin/blob/master/koin-projects/docs/reference/koin-android/fragment-factory.md

### PR DESCRIPTION
**Pull request by floschu**
Adds [koin fragment-factory](https://github.com/InsertKoinIO/koin/blob/master/koin-projects/docs/reference/koin-android/fragment-factory.md) to enable constructor injection in Fragments.
Fixes #15

### CODE REVIEW

**Review by FlowMo7 — APPROVED** [review]
LGTM! :rocket: 

Juast as a general thought: I would like to add a link to the [koin fragment factory](https://github.com/InsertKoinIO/koin/blob/master/koin-projects/docs/reference/koin-android/fragment-factory.md) in the readme or in the code as comments, though, as I think Fragment constructor injection can be misleading for developers not familiar with the concept, which forget to add the declaration of the fragment in the module.

**Review by daniel-diamir — COMMENTED** [review]
lgtm

one question came to mind: use lifecycle scope when injecting fragment?
```
scope<MyActivity> {
        fragment { MyFragment(get()) }
    }
```

**Comment by floschu** [comment]
> lgtm
> 
> one question came to mind: use lifecycle scope when injecting fragment?
> 
> ```
> scope<MyActivity> {
>         fragment { MyFragment(get()) }
>     }
> ```

why

**Comment by daniel-diamir** [comment]
> > lgtm
> > one question came to mind: use lifecycle scope when injecting fragment?
> > ```
> > scope<MyActivity> {
> >         fragment { MyFragment(get()) }
> >     }
> > ```
> 
> why

not in this case.. was more of a general question on the use of scopes etc. since I'm not familiar with the template or koin. 
'resolved' via slack.

usage of scope, fragment injection maybe smthg to talk about in ADM.

**Review by daniel-diamir — APPROVED** [review]

**Review by AlexGrafl — COMMENTED** [review]
(Disclaimer: I have not read the documentation to Koin Fragment Factory) Is this approach compatible with the Jetpack Navigation Component?

**Comment by floschu** [comment]
> (Disclaimer: I have not read the documentation to Koin Fragment Factory) Is this approach compatible with the Jetpack Navigation Component?

Yes: https://github.com/tailoredmedia/AndroidAppTemplateExample/pull/6

**Pull request merged**
