### PR TITLE
Fix missing character in application class filename

### LINKED ISSUE #3: setup.sh omits the first character in application filename
Starting the setup-script with the following parameters:
```
App name (e.g. MainGau, note: without the suffix 'App'): Test
Package name (e.g. com.tailoredapps.maingau): com.example.test
```
Will lead into the filename `estApp.kt` of the application class, whereas the class-name is set correctly to `TestApp` and packages are all moved correctly.

This was tested on a Ubuntu 18.04.2 LTS.

However, on Windows the filename is correctly set as `TestApp.kt`.

It seems that the second substring here (https://github.com/tailoredmedia/AndroidAppTemplate/blob/master/setup.sh#L42) leads to a missing character.
Changing that to a `substr($0,1)` fixes this on ubuntu and seems to have no effect (still correct behaviour) on Windows.

### PR DESCRIPTION
**Pull request by FlowMo7**
fixes #3

### CODE REVIEW

**Review by Quadrox — APPROVED** [review]

**Comment by migos** [comment]
@FlowMo7 please test the new changes

**Comment by FlowMo7** [comment]
@migos Thanks, for me it still works on my machine (Ubuntu 18.04.2 LTS) with the newest changes.

**Review by AlexGrafl — APPROVED** [review]
Works on mac after bash update to 5.0.x.

**Review by migos — COMMENTED** [review]
Fixed script for windows. Should work now.

**Review by migos — APPROVED** [review]

**Pull request merged**
